### ISSUE TITLE
Texture artifacts

### ISSUE THREAD

**Issue by ghost** [EvilPudding/candle#7]
Some texture artifacts appear in Shift3D and twinpeaks demos when ran on a Linux system with a GTX 980 GPU and proprietary NVidia drivers.
![2019-09-19-203414_3440x1440_scrot](https://user-images.githubusercontent.com/43107265/65263280-93f66600-db0c-11e9-9fd9-15d5cde31c50.png)
![2019-09-19-202841_3440x1440_scrot](https://user-images.githubusercontent.com/43107265/65263281-93f66600-db0c-11e9-96d0-fbe3838f992b.png)
![2019-09-19-202509_3440x1440_scrot](https://user-images.githubusercontent.com/43107265/65263282-948efc80-db0c-11e9-8885-8cf4a9b04ae0.png)
![2019-09-19-201101_3440x1440_scrot](https://user-images.githubusercontent.com/43107265/65263285-9789ed00-db0c-11e9-8d6d-84d3f42478d5.png)

**Comment by EvilPudding** [comment]
Those are shadow artifacts, and I think most of them are fixed on the newest candle version, I just haven't had time to update those projects to use the later version. Thanks for reporting it though, will try to update it later today.

I should have added alternative shadow algorithms though, since the one being used is an approximation which has some known problems.
