### ISSUE TITLE
Does not compile on linux

### ISSUE THREAD

**Issue by kyx0r** [EvilPudding/candle#9]
Tested on Arch and Void linux systems. Build fails at when packager tries to do something. 
<a href="https://ibb.co/TwgVpYh"><img src="https://i.ibb.co/4FV69KN/2020-12-21-210706-2129x334-scrot.png" alt="2020-12-21-210706-2129x334-scrot" border="0"></a>

Let me know if you need more info.

**Comment by EvilPudding** [comment]
What's the error that's stopping the build? The screenshot looks like it just includes a note. Is that the only thing reported?

**Comment by kyx0r** [comment]
packager.c is bugged. This error is being printed.
https://github.com/EvilPudding/candle/blob/master/buildtools/packager.c#L324

**Comment by EvilPudding** [comment]
I'm not being able to reproduce it, but I added some lines to print the specific error cause. If that doesn't help narrow it down, I'd be thankful for a minimal example that reproduces it.

**Comment by kyx0r** [comment]
mkdir -p build
mkdir -p build/components
ar rs build/candle.a  build/candle.o  build/components/ambient.o  build/components/attach.o  build/components/axis.o  build/components/bone.o  build/components/camera.o  build/components/decal.o  build/components/destroyed.o  build/components/editlook.o  build/components/field.o  build/components/freelook.o  build/components/freemove.o  build/components/light.o  build/components/model.o  build/components/name.o  build/components/node.o  build/components/skin.o  build/components/spatial.o  build/components/sprite.o  build/components/timeline.o  build/systems/controller.o  build/systems/editmode.o  build/systems/keyboard.o  build/systems/mouse.o  build/systems/nodegraph.o  build/systems/render_device.o  build/systems/sauces.o  build/systems/window.o  build/formats/obj.o  build/formats/ply.o  build/utils/drawable.o  build/utils/file.o  build/utils/gl.o  build/utils/glutil.o  build/utils/heap.o  build/utils/loader.o  build/utils/material.o  build/utils/mesh.o  build/utils/nk.o  build/utils/noise.o  build/utils/renderer.o  build/utils/shader.o  build/utils/shaders_default.o  build/utils/str.o  build/utils/texture.o  build/utils/vector.o  build/vil/vil.o  build/ecs/ecm.o  build/ecs/entity.o  build/third_party/glfw/src/context.o  build/third_party/glfw/src/init.o
build/third_party/glfw/src/input.o  build/third_party/glfw/src/monitor.o  build/third_party/glfw/src/window.o  build/third_party/glfw/src/vulkan.o  build/third_party/glfw/src/egl_context.o  build/third_party/glfw/src/glx_context.o  build/third_party/glfw/src/linux_joystick.o  build/third_party/glfw/src/osmesa_context.o  build/third_party/glfw/src/posix_thread.o  build/third_party/glfw/src/posix_time.o  build/third_party/glfw/src/x11_init.o  build/third_party/glfw/src/x11_monitor.o  build/third_party/glfw/src/x11_window.o  build/third_party/glfw/src/xkb_unicode.o  build/third_party/tinycthread/source/tinycthread.o
mkdir -p build/systems
mkdir -p build/utils
build/packager ../
mkdir -p build/formats
mkdir -p build/vil
mkdir -p build/ecs
mkdir -p build/third_party/glfw/src
mkdir -p build/third_party/tinycthread/source
rm -f build/res
ar: creating build/candle.a
archiving '..//cover8.jpg'
Failed append
invalid filename
make: *** [Makefile:130: data_zip] Error 1
make: *** Waiting for unfinished jobs....


The path that packager.c takes is wrong, as you can see for some reason it tries to archieve file in the .. directory which absolutely make no logical sense. cover8.jpg is a completely unrelated file that is present in my home directory.

**Comment by kyx0r** [comment]
Further when trying to compile under muslC one will get bunch of compiler errors like these:
https://0x0.st/ozLU.txt

In short, this project needs a lot more polishing and work done, it's the little things that matter. I hope
with time you will be able to strip down all the 3rd party libs down to exactly things that you use. Remove
use of bad build systems like make and provide amalgamated version, so that one can use any compiler like tcc
for example and compile the whole thing with 1 command in < 5 s. Also properly comform to posix and get rid of any Gnu-isms if there are any.

**Comment by kyx0r** [comment]
One last remark; high quality software is not built by slapping bunch of 3rd party libraries together and making the thing "work". It comes down to a deliberate process of actually reading the code of 3rd party libs in question, figuring out what functionality is needed from them, looking for better ways to implement things, and lastly incorporating the said portions into your main code. If at any point in time your code looks unnatural, you know you have failed one of the steps. The codebase should be small and easy to read. I am sure you aren't utilizing all 65000 lines of code there is to nuklear, for education purposes it is nothing but harmful. If you want your code to be used by other people, make it small and manageble. This is a hard thing to do, we all have our limits but given that this might be the passion project of your life it may be worth doing so. Before thinking about adding new features think about perfecting everything else you have so far (and there's a lot!). 

That's just some of my wishes, as I see the project does have a potential at becoming something bigger.
Of course everything lies into your discretion.

Kind Regards,
Kyryl.

**Comment by EvilPudding** [comment]
I agree with many of the things you said, and I appreciate you taking time to look at and comment on the project, but disagree with others, and I hope you don't take it as me being defensive. Most of the discussion is off-topic on the specific issue, but idc, will try to address the technical issues in this comment, and discuss the other issues on a separate one.

> Further when trying to compile under muslC one will get bunch of compiler errors like these:

The warnings reported here seem to be related to improper C89 compliance by the standard headers being included. As far as I'm aware, C89 does not define `round` and `roundf` (and those other math functions), which is where the conflict is happening. If the C89 standard does define `round` and `roundf`, then I'd like to read it, and figure out why `gcc` doesn't define it under C89 so that I could know how to check if I should define it myself or not. I am open to renaming the function to avoid similar problems, but I don't know if I should.

> The path that packager.c takes is wrong, as you can see for some reason it tries to archieve file in the .. directory which absolutely make no logical sense. cover8.jpg is a completely unrelated file that is present in my home directory.

It should try to archive the `..` directory if that's the resource variable passed to the makefile. What command are you using to build the project? If you look at how the build system is supposed to be called in the sample project provided, it calls the engine's makefile with the `SAUCES` variable set to the directory where the projects resources are supposed to live. That is how it works right now, I'd be open to suggestions of better ways, but calling it improperly is going to have unintended effects. If you did call it properly, then there is some bug with the build scripts, not packager or the libraries it uses.

**Comment by EvilPudding** [comment]
> In short, this project needs a lot more polishing and work done, it's the little things that matter

I agree 100% with this, which is why I included `early development stages` in the first line of the readme. I don't think the project is ready to be used by others for any practical application. As you can probably tell, working on the engine is not my full time job, or even part time job. It's something I pick up when I am curious of how a specific technique is achieved, or I have an idea for a technique I haven't seen anywhere else, and get excited to try my hand at it. I know that that might get in the way of focusing on cleaning it up, but as you can see from the commit frequency, it's already rare that I get excited about a feature I want to implement, so something is better than nothing. Right now, the reasons the project is public are:

1. So I can get project direction feedback similar to the one you gave;
2. So I can get technical feedback
3. So people who are curious about how a specific graphical effect I've shared somewhere else was made can see how it was done;

> I hope with time you will be able to strip down all the 3rd party libs down to exactly things that you use

This is probably one of the things I most disagree with what you said. It's already time consuming to clean up my code, I am not interested in cleaning up other libraries, and I will use libraries as much as a black box as I can get away with, unless I find big issues that make me consider switching libraries, or making my own implementation. Not doing so in a hobby project would hinder progress in all aspects, be it features or code readability.

> I am sure you aren't utilizing all 65000 lines of code there is to nuklear, for education purposes it is nothing but harmful. If you want your code to be used by other people, make it small and manageble.

If someone is exploring my project, they can tell I'm including nuklear as a submodule, unless they're interested in exploring nuklear, they wouldn't go exploring those 65000 lines, they would just realize what it does and move on. Ironically enough, if I had my own implementation, with 5000 lines instead of 65000, it would actually take more time to explore my repo than me including nuklear because it would be custom code, specific to the repo, with its own possible issues. All that being said, I'm not against having my own GUI toolkit in the project, but right now it would just be more work for very little gain, which I wouldn't mind doing if I had good ideas I wanted to try implementing.

> One last remark; high quality software is not built by slapping bunch of 3rd party libraries together and making the thing "work". It comes down to a deliberate process of actually reading the code of 3rd party libs in question, figuring out what functionality is needed from them, looking for better ways to implement things, and lastly incorporating the said portions into your main code

I just disagree with this. If I think I can do something a library does, but better, I will try my hand at it. Otherwise I will use libraries, which will keep the amount of code I have to maintain and worry about smaller, and allow me to focus on the ideas I have for new graphics algorithms, or optimizing the performance on the slowest parts of the program, which right now are shader related. With that said, if someone came to me and said that a library I'm using is causing issues, I would look into it, and do some of the steps you said there.

> Remove use of bad build systems like make [...] and provide amalgamated version, so that one can use any compiler like tcc

I'm open to suggestions. I use `make` and `bat`, because they come pre-installed in the systems I'm targeting. I thought about moving most of the dependency and reuse management made by `make` into my own C file, which would allow compiling it through `bash`, and remove a lot of duplication between the `bat` and `make` scripts, but haven't decided if that's the right way yet. One of the biggest problems, and the reason I can't just provide an amalgamated version, or even provide the engine as a dynamic library that could just be plugged into any other project, is that there are some steps that need to be run during compilation, like resource packing and plugin compilation, that would just not work when used like that. If you have ideas on how that could work, I'd be happy to consider them.

> Before thinking about adding new features think about perfecting everything else you have so far (and there's a lot!).

You're right. Even if I don't agree with some stuff, and we could have some back and forth on them (if you care to), I agree with that above all. There is a lot of stuff to clean up, the project was mostly me trying to add features, and trying to refactor to accommodate those features. I did have a lot of commits and thought put into cleaning things up, like if you go back in the commit history and see how the project specific build script evolved, but there is still much to do.

Thank you for your time.

**Comment by EvilPudding** [comment]
Maybe a small correction / clarification. When I said I disagree with:

> figuring out what functionality is needed from them, looking for better ways to implement things, and lastly incorporating the said portions into your main code

I didn't mean to say that projects that do this are wrong or worse, and if I did, I take it back. I would probably say those projects are much better, and if it came at no expense I would rather Candle were also like that. It's just that when trying to get things done, I've not yet regretted using libraries, but I've regretted not using them in some cases, even if that does make the project less of a perfect diamond.
